# unmounting /mnt makes the image usable for now.

- name: unmount /mnt
  mount: name=/mnt src='/dev/vdb' fstype=ext3 state=unmounted


# tasks for autopartion and autoformat and mount /dev/vdc1
# mounting currently disabled

- name: Check for /dev/vdc1
  stat: path=/dev/vdc1
  register: vdc_status
  tags: 
  - data_volume

# Mount devices
- name: Partition assign label
  command: bash -c "/usr/bin/yes No | /sbin/parted  /dev/vdc mklabel msdos"
  when: not vdc_status.stat.exists
  tags: 
  - data_volume

- name: Partition create
  command: bash -c "/usr/bin/yes No | /sbin/parted -a optimal /dev/vdc mkpart primary 0% 100%"
  when: not vdc_status.stat.exists
  tags: 
  - data_volume

- name: create filesystem(s)
  filesystem: fstype=ext4 dev=/dev/vdc1
  tags: 
  - data_volume

#- name: mount data
#  mount: name=/mnt/data src='/dev/vdc1' fstype=ext4 state=present
