- name: Create local temp dir
  file:
    path: "/tmp/{{ comp_home }}"
    state: directory
    mode: 0700
  delegate_to: localhost

- name: Fetch production comp
  get_url:
    url: "{{ chipster_production_tarball }}"
    dest: "/tmp/{{ comp_home }}/chipster_production.tgz"
  delegate_to: localhost
  when: comp_home == "mylly"

- name: extract production comp
  command: /bin/tar xfzv chipster_production.tgz chipster/comp chipster/shared/bin chipster/shared/lib --exclude="chipster/comp/bin/linux-x86-32/*"
  args:
    chdir: "/tmp/{{ comp_home }}/"
  delegate_to: localhost
  when: comp_home == "mylly"

- name:   Synchronise mylly-dev 1 
  local_action: command /usr/bin/rsync -r --include 'comp' --include 'comp/bin/' --include 'comp/bin/chipster-comp' --include 'comp/bin/linux-x86-64**' --include 'comp/conf**' --include 'comp/security**' --include 'shared/' --include 'shared/bin**' --include 'shared/lib/' --include 'shared/lib/*' --exclude '*' chipster@vm0171.kaj.pouta.csc.fi:/opt/chipster/ /tmp/{{ comp_home}}/chipster/
  when: comp_home == "mylly-dev"

- name: Ensure user kp-ruser
  local_action:
    module: lineinfile
    path: "/tmp/{{ comp_home }}/chipster/comp/bin/linux-x86-64/chipster-comp"
    regexp: "^#?RUN_AS_USER="
    line: "RUN_AS_USER=kp-ruser"

- name: Synchronize comp 2
  local_action: command /usr/bin/rsync -r /tmp/{{ comp_home }}/chipster/ kp-ruser@taito.csc.fi:~/{{ comp_home }}/generic_node/

- name: setup node dirs
  file:
    path: "{{ comp_home }}/{{ item }}/comp/logs"
    state: directory
    mode: 0700
  with_items:
   - "{{ nodes }}"

- name: setup jobs-data
  file:
    src: /wrk/kp-ruser/
    dest: "/homeappl/home/kp-ruser/{{ comp_home }}/{{ item }}/comp/jobs-data"
    state: link
  with_items:
   - "{{ nodes }}"


- name: copy comp/bin
  command: cp -rf "/homeappl/home/kp-ruser/{{ comp_home }}/generic_node/comp/bin/"  "/homeappl/home/kp-ruser/{{ comp_home }}/{{ item }}/comp/"
  with_items:
   - "{{ nodes }}"


- name: setup node symlinks
  file:
    src: "/homeappl/home/kp-ruser/{{ comp_home }}/generic_node/{{ item[1] }}"
    dest: "/homeappl/home/kp-ruser/{{ comp_home }}/{{ item[0] }}/{{ item[1] }}"
    state: link
  with_nested:
   - "{{ nodes }}"
   - "{{ shared_comp_dirs }}"

- name: Copy mylly_comp
  copy:
    src:  mylly_comp
    dest: "{{ comp_home }}/mylly_comp"
    mode: 0700

