# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#

- name: Create security group
  os_security_group: name=chipster-sg
  tags:
   - create_vm

- name: Add rule to security group
  os_security_group_rule:
    security_group: chipster-sg
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  tags:
   - create_vm

- name: Add rule to security group
  os_security_group_rule:
    security_group: chipster-sg
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  tags:
   - create_vm

- name: Create a virtual machine
  register: result
  os_server:
    name: cielipankki
    image: Chipster_3.6.3_Root
    flavor: small
    key_name: "{{ chipster_key }}"
    security_groups: "{{ chipster_security_groups }}"
    nics:
     - net-name: "{{ chipster_network }}"
    floating_ips:
     - "{{ floating_ip }}"
  tags:
   - create_vm
 
- name: Add new host to inventory
  add_host: name={{ floating_ip }} groups=new
  
- name: clear ssh known_hosts
  known_hosts: name={{ floating_ip }} state=absent
  when: result | changed
  tags:
   - create_vm

- name: Wait for instance to be ready
  wait_for: host={{ floating_ip }} port=22 search_regex=OpenSSH delay=5
  tags:
   - create_vm