# put very Kielipankki-specific tasks here.

- name: update Kielipankki-mylly repo
  git:
    repo: https://github.com/CSC-IT-Center-for-Science/Kielipankki-mylly.git
    update: yes
    dest: /home/chipster/Kielipankki-mylly
    version: dev-tools
    
- name: Remove tools dir
  file:
    path: /opt/chipster/toolbox/tools
    state: absent

- name: Set up tools dir
  file:
    src: /home/chipster/Kielipankki-mylly/tools/
    dest: /opt/chipster/toolbox/tools
    state: directory
    owner: chipster
    group: chipster
    mode: 0755

- name: Sync from Git
  command: /home/chipster/Kielipankki-mylly/update_tools.sh
  args:
    creates: /opt/chipster/toolbox/tools/kielipankki
  
- name: "Setup git pull in cron"
  cron:
    name: "Update Mylly tools"
    minute: "*/5"
    job: "/home/chipster/Kielipankki-mylly/update_tools.sh > /dev/null"
