
- name: Enable admin web
  become: yes
  become_user: chipster
  command: ./configure.sh edit manager set manager/start-admin true
  args:
    chdir: /opt/chipster/

- name: Set admin web password
  become: yes
  become_user: chipster
  command: ./configure.sh edit manager set manager/admin-password "{{ lookup('password', 'admin_web_password') }}"
  args:
    chdir: /opt/chipster/

