- name: Firewall
  ufw: policy=deny
   
- name: Set firewall rules for web traffic and SSH
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
  - http
  - https
  - ssh
  - 8080
  - 8081
  - 61616


- name: Enable UFW
  ufw: state=enabled

